// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/api"
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/api/handler"
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/config"
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/db"
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/repository"
	"github.com/nikhilnarayanan623/go-hls-streaming-clean-arch/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.Server, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	videoRepository := repository.NewVideoRepository(gormDB)
	videoUseCase := usecase.NewVideoUseCase(videoRepository)
	videoHandler := handler.NewVideoHandler(videoUseCase)
	audioRepository := repository.NewAudioRepository(gormDB)
	audioUseCase := usecase.NewAudioUseCase(audioRepository)
	audioHandler := handler.NewAudioHandler(audioUseCase)
	server := http.NewServerHTTP(cfg, videoHandler, audioHandler)
	return server, nil
}
